/* ==========================================================================
   POCKETPE - CONFIGURATION & DEFAULT DATA
   ========================================================================== */

export const APP_CONFIG = {
  APP_NAME: 'PocketPe',
  APP_VERSION: '2.4.0',
  TAGLINE: 'Every rupee has a purpose.',
  STORAGE_KEYS: {
    APP_STATE: 'pocketpe_app_state_v3',
    THEME: 'pocketpe_theme',
    ACCENT: 'pocketpe_accent',
    LEARNED_MERCHANTS: 'pocketpe_learned_merchants',
    HAS_ONBOARDED: 'pocketpe_has_onboarded',
    SUPABASE_URL: 'pocketpe_supabase_url',
    SUPABASE_ANON_KEY: 'pocketpe_supabase_anon_key',
    USER_SCOPED_PREFIX: 'pocketpe_user_',
  },
  DEFAULT_ACCENT: 'blue',
  DEFAULT_THEME: 'system',
  SUPABASE: {
    // Default project credentials (can be overridden via .env, window.__ENV__, localStorage, or in-app settings)
    DEFAULT_URL: (typeof window !== 'undefined' && window.__ENV__?.SUPABASE_URL) || 'https://gevjalpbbqesuggnllsx.supabase.co',
    DEFAULT_ANON_KEY: (typeof window !== 'undefined' && (window.__ENV__?.SUPABASE_ANON_KEY || window.__ENV__?.SUPABASE_PUBLISHABLE_KEY)) || 'sb_publishable_JSsZMAf2wmDSIIu2zEeKAQ_0YDE2i_w',
  },
};

export const WALLET_PRESETS = [
  { name: 'Food & Dining', icon: '🍔', color: '#f59e0b', category: 'Food & Dining' },
  { name: 'Transport & Fuel', icon: '🚗', color: '#06b6d4', category: 'Transport & Fuel' },
  { name: 'Rent & Housing', icon: '🏠', color: '#6366f1', category: 'Housing' },
  { name: 'College & Courses', icon: '🎓', color: '#8b5cf6', category: 'College & Education' },
  { name: 'Savings & Growth', icon: '💰', color: '#10b981', category: 'Savings & Investment' },
  { name: 'Family & Parents', icon: '👨‍👩‍👧', color: '#3b82f6', category: 'Family' },
  { name: 'Travel & Trips', icon: '✈️', color: '#14b8a6', category: 'Travel' },
  { name: 'Friends & Social', icon: '🤝', color: '#ec4899', category: 'Friends & Social' },
  { name: 'Health & Care', icon: '🩺', color: '#ef4444', category: 'Health & Wellness' },
  { name: 'Entertainment', icon: '🎬', color: '#f97316', category: 'Entertainment' },
];

export const INITIAL_WALLETS = [
  {
    id: 'wallet_food',
    name: 'Food',
    icon: '🍔',
    color: '#f59e0b',
    balance: 0,
    targetAmount: 2500,
    monthlyLimit: 2500,
    allocationPercentage: 25,
    category: 'Food & Dining',
    isFreeMoney: false,
    frequency: 'Every time I receive money',
  },
  {
    id: 'wallet_transport',
    name: 'Transport',
    icon: '🚗',
    color: '#06b6d4',
    balance: 0,
    targetAmount: 1000,
    monthlyLimit: 1200,
    allocationPercentage: 15,
    category: 'Transport & Fuel',
    isFreeMoney: false,
    frequency: 'Every time I receive money',
  },
  {
    id: 'wallet_savings',
    name: 'Savings',
    icon: '💰',
    color: '#10b981',
    balance: 0,
    targetAmount: 2500,
    monthlyLimit: 0,
    allocationPercentage: 20,
    category: 'Savings & Investment',
    isFreeMoney: false,
    frequency: 'Every time I receive money',
  },
  {
    id: 'wallet_college',
    name: 'College',
    icon: '🎓',
    color: '#8b5cf6',
    balance: 0,
    targetAmount: 2000,
    monthlyLimit: 2000,
    allocationPercentage: 15,
    category: 'College & Education',
    isFreeMoney: false,
    frequency: 'Every time I receive money',
  },
  {
    id: 'wallet_friends',
    name: 'Friends',
    icon: '🤝',
    color: '#ec4899',
    balance: 0,
    targetAmount: 1500,
    monthlyLimit: 1500,
    allocationPercentage: 10,
    category: 'Friends & Social',
    isFreeMoney: false,
    frequency: 'Every time I receive money',
  },
  {
    id: 'wallet_medical',
    name: 'Medical',
    icon: '💊',
    color: '#ef4444',
    balance: 0,
    targetAmount: 2000,
    monthlyLimit: 2000,
    allocationPercentage: 10,
    category: 'Medical',
    isFreeMoney: false,
    frequency: 'Every time I receive money',
  },
  {
    id: 'wallet_free',
    name: 'Free Money',
    icon: '✨',
    color: '#3b82f6',
    balance: 0,
    targetAmount: 0,
    monthlyLimit: 0,
    allocationPercentage: 5,
    category: 'Unallocated Cushion',
    isFreeMoney: true,
    frequency: 'Unallocated reserve',
  },
];

export const INITIAL_TRANSACTIONS = [];

export const INITIAL_COMMITMENTS = [];

export const KNOWN_MERCHANT_DIRECTORY = [
  {
    id: 'm_abc_rest',
    name: 'ABC Restaurant',
    upiId: 'abcrestaurant@hdfcbank',
    category: 'Food & Dining',
    defaultAmount: 350,
    icon: '🍽️',
    mcc: '5812',
    description: 'Popular diner in downtown',
    matchingWallet: 'wallet_food',
  },
  {
    id: 'm_starbucks',
    name: 'Starbucks Coffee',
    upiId: 'starbucks.order@icici',
    category: 'Food & Dining',
    defaultAmount: 220,
    icon: '☕',
    mcc: '5814',
    description: 'Beverages and pastries',
    matchingWallet: 'wallet_food',
  },
  {
    id: 'm_uber',
    name: 'Uber / City Taxi',
    upiId: 'uber.india@axisbank',
    category: 'Transport & Fuel',
    defaultAmount: 240,
    icon: '🚕',
    mcc: '4121',
    description: 'Ride hailing transit',
    matchingWallet: 'wallet_transport',
  },
  {
    id: 'm_shell',
    name: 'Shell Fuel Station',
    upiId: 'shell.petrol@paytm',
    category: 'Transport & Fuel',
    defaultAmount: 500,
    icon: '⛽',
    mcc: '5541',
    description: 'Vehicle petrol / diesel refill',
    matchingWallet: 'wallet_transport',
  },
  {
    id: 'm_apollo',
    name: 'Apollo Pharmacy',
    upiId: 'apollo.retail@hdfcbank',
    category: 'Health & Wellness',
    defaultAmount: 420,
    icon: '💊',
    mcc: '5912',
    description: 'Medicine & healthcare supplies',
    matchingWallet: 'wallet_free',
  },
  {
    id: 'm_campus_books',
    name: 'Campus Book Store',
    upiId: 'campusbooks@sbi',
    category: 'College & Education',
    defaultAmount: 650,
    icon: '📚',
    mcc: '5942',
    description: 'Semester reference books & stationery',
    matchingWallet: 'wallet_college',
  },
  {
    id: 'm_barber',
    name: 'XYZ Barber & Salon',
    upiId: 'xyzsalon@okaxis',
    category: 'Personal Care',
    defaultAmount: 300,
    icon: '💈',
    mcc: '7230',
    description: 'Grooming & haircut',
    matchingWallet: 'wallet_free',
  },
  {
    id: 'm_zara',
    name: 'Zara Lifestyle',
    upiId: 'zara.india@kotak',
    category: 'Shopping & Apparel',
    defaultAmount: 1200,
    icon: '🛍️',
    mcc: '5651',
    description: 'Clothing & lifestyle',
    matchingWallet: 'wallet_free',
  },
  {
    id: 'm_friend_rohan',
    name: 'Pay Friend (Rohan)',
    upiId: 'rohan.sharma@okhdfcbank',
    category: 'Friends & Social',
    defaultAmount: 500,
    icon: '👤',
    mcc: '0000',
    description: 'Personal peer-to-peer payback',
    matchingWallet: 'wallet_friends',
  },
  {
    id: 'm_electricity_refund',
    name: 'Electricity Helpdesk',
    upiId: 'powerbill.helpdesk@ybl',
    category: 'Housing',
    defaultAmount: 2450,
    icon: '⚠️',
    mcc: '4900',
    description: 'Reported: Unverified utility collection handle',
    matchingWallet: 'wallet_free',
  },
  {
    id: 'm_lottery_scam',
    name: 'Lucky Draw Office',
    upiId: 'reward.claim981@okaxis',
    category: 'General Expense',
    defaultAmount: 999,
    icon: '🚨',
    mcc: '0000',
    description: 'Reported: High-risk fee collection handle',
    matchingWallet: 'wallet_free',
  },
];
export const DIRECTORY_MERCHANTS = KNOWN_MERCHANT_DIRECTORY;

export const INITIAL_FRAUD_DATA = {
  // Threshold: min 5 reports to trigger community risk badge
  minReportThreshold: 5,
  reports: [
    // 8 reports for powerbill.helpdesk@ybl
    { id: 'rep_01', reporterId: 'usr_101', reporterTrust: 1.0, reportedUpiId: 'powerbill.helpdesk@ybl', reason: 'Fake collect request', details: 'Sent fake electricity disconnection bill', createdAt: new Date(Date.now() - 2 * 86400000).toISOString(), deviceId: 'dev_101' },
    { id: 'rep_02', reporterId: 'usr_102', reporterTrust: 0.9, reportedUpiId: 'powerbill.helpdesk@ybl', reason: 'Fake collect request', details: 'Claimed to be Power Corporation', createdAt: new Date(Date.now() - 3 * 86400000).toISOString(), deviceId: 'dev_102' },
    { id: 'rep_03', reporterId: 'usr_103', reporterTrust: 1.0, reportedUpiId: 'powerbill.helpdesk@ybl', reason: 'Impersonation', details: 'Pretending to be BESCOM agent', createdAt: new Date(Date.now() - 4 * 86400000).toISOString(), deviceId: 'dev_103' },
    { id: 'rep_04', reporterId: 'usr_104', reporterTrust: 0.8, reportedUpiId: 'powerbill.helpdesk@ybl', reason: 'Fake collect request', details: 'Threatened immediate power cut', createdAt: new Date(Date.now() - 5 * 86400000).toISOString(), deviceId: 'dev_104' },
    { id: 'rep_05', reporterId: 'usr_105', reporterTrust: 1.0, reportedUpiId: 'powerbill.helpdesk@ybl', reason: 'Repeated money requests', details: 'Spamming ₹2,450 collect requests', createdAt: new Date(Date.now() - 6 * 86400000).toISOString(), deviceId: 'dev_105' },
    { id: 'rep_06', reporterId: 'usr_106', reporterTrust: 0.95, reportedUpiId: 'powerbill.helpdesk@ybl', reason: 'Fake collect request', details: 'Phishing collect notification', createdAt: new Date(Date.now() - 7 * 86400000).toISOString(), deviceId: 'dev_106' },
    { id: 'rep_07', reporterId: 'usr_107', reporterTrust: 0.85, reportedUpiId: 'powerbill.helpdesk@ybl', reason: 'Other', details: 'Scam caller asked to approve UPI request', createdAt: new Date(Date.now() - 8 * 86400000).toISOString(), deviceId: 'dev_107' },
    { id: 'rep_08', reporterId: 'usr_108', reporterTrust: 1.0, reportedUpiId: 'powerbill.helpdesk@ybl', reason: 'Fake collect request', details: 'Fraudulent utility bill', createdAt: new Date(Date.now() - 9 * 86400000).toISOString(), deviceId: 'dev_108' },

    // 12 reports for reward.claim981@okaxis
    ...Array.from({ length: 12 }).map((_, i) => ({
      id: `rep_lottery_${i + 1}`,
      reporterId: `usr_20${i + 1}`,
      reporterTrust: 0.9,
      reportedUpiId: 'reward.claim981@okaxis',
      reason: 'Prize or lottery scam',
      details: 'SMS claimed I won ₹50,000, asked ₹999 fee',
      createdAt: new Date(Date.now() - (i + 1) * 86400000).toISOString(),
      deviceId: `dev_20${i + 1}`,
    })),

    // 1 isolated report for ABC Restaurant (below threshold of 5 -> Low / not flagged)
    { id: 'rep_abc_01', reporterId: 'usr_999', reporterTrust: 0.5, reportedUpiId: 'abcrestaurant@hdfcbank', reason: 'Other', details: 'Order delayed', createdAt: new Date(Date.now() - 40 * 86400000).toISOString(), deviceId: 'dev_999' },
  ],
  interactions: {
    'powerbill.helpdesk@ybl': ['usr_101', 'usr_102', 'usr_103', 'usr_104', 'usr_105', 'usr_106', 'usr_107', 'usr_108', 'usr_109', 'usr_110'],
    'reward.claim981@okaxis': ['usr_201', 'usr_202', 'usr_203', 'usr_204', 'usr_205', 'usr_206', 'usr_207', 'usr_208', 'usr_209', 'usr_210', 'usr_211', 'usr_212', 'usr_213', 'usr_214'],
    'abcrestaurant@hdfcbank': Array.from({ length: 60 }).map((_, i) => `usr_abc_${i}`),
    'rohan.sharma@okhdfcbank': ['usr_001', 'usr_friend_1', 'usr_friend_2', 'usr_friend_3'],
    'starbucks.order@icici': Array.from({ length: 45 }).map((_, i) => `usr_sb_${i}`),
  },
  upiRegistry: {
    'powerbill.helpdesk@ybl': {
      upiId: 'powerbill.helpdesk@ybl',
      registeredName: 'Raju K. (Individual)',
      handleName: 'Electricity Board Support Desk',
      registeredDaysAgo: 4,
      collectVelocity1h: 18,
      nameMismatch: true,
    },
    'reward.claim981@okaxis': {
      upiId: 'reward.claim981@okaxis',
      registeredName: 'Prepaid SIM Card #882',
      handleName: 'Lucky Draw Reward Office',
      registeredDaysAgo: 2,
      collectVelocity1h: 27,
      nameMismatch: true,
    },
    'abcrestaurant@hdfcbank': {
      upiId: 'abcrestaurant@hdfcbank',
      registeredName: 'ABC Gourmet Diners Pvt Ltd',
      handleName: 'ABC Restaurant',
      registeredDaysAgo: 640,
      collectVelocity1h: 2,
      nameMismatch: false,
    },
    'rohan.sharma@okhdfcbank': {
      upiId: 'rohan.sharma@okhdfcbank',
      registeredName: 'Rohan Sharma',
      handleName: 'Rohan Sharma',
      registeredDaysAgo: 380,
      collectVelocity1h: 1,
      nameMismatch: false,
    },
  },
  appeals: [],
};

export const INITIAL_COLLECT_REQUESTS = [];

export const INITIAL_SPLIT_DATA = {
  groups: [],
  groupMembers: [],
  expenses: [],
  settlements: [],
};

