/* ==========================================================================
   POCKETPE - CONFIGURATION & DEFAULT DATA
   ========================================================================== */

export const APP_CONFIG = {
  APP_NAME: 'PocketPe',
  APP_VERSION: '2.4.0',
  TAGLINE: 'Every rupee has a purpose.',
  STORAGE_KEYS: {
    APP_STATE: 'pocketpe_app_state_v2',
    THEME: 'pocketpe_theme',
    ACCENT: 'pocketpe_accent',
    LEARNED_MERCHANTS: 'pocketpe_learned_merchants',
    HAS_ONBOARDED: 'pocketpe_has_onboarded',
  },
  DEFAULT_ACCENT: 'blue',
  DEFAULT_THEME: 'system',
};

export const WALLET_PRESETS = [
  { name: 'Food & Dining', icon: '🍔', color: '#f59e0b', category: 'Food & Dining' },
  { name: 'Transport & Fuel', icon: '🚗', color: '#06b6d4', category: 'Transport & Fuel' },
  { name: 'Rent & Housing', icon: '🏠', color: '#6366f1', category: 'Housing' },
  { name: 'College & Courses', icon: '🎓', color: '#8b5cf6', category: 'College & Education' },
  { name: 'Savings & Growth', icon: '💰', color: '#10b981', category: 'Savings & Investment' },
  { name: 'Family & Parents', icon: '👨‍👩‍👧', color: '#3b82f6', category: 'Family' },
  { name: 'Travel & Trips', icon: '✈️', color: '#14b8a6', category: 'Travel' },
  { name: 'Friends & Social', icon: '🤝', color: '#ec4899', category: 'Friends & Social' },
  { name: 'Health & Care', icon: '🩺', color: '#ef4444', category: 'Health & Wellness' },
  { name: 'Entertainment', icon: '🎬', color: '#f97316', category: 'Entertainment' },
];

export const INITIAL_WALLETS = [
  {
    id: 'wallet_food',
    name: 'Food',
    icon: '🍔',
    color: '#f59e0b',
    balance: 2000,
    targetAmount: 2500,
    monthlyLimit: 2500,
    allocationPercentage: 25,
    category: 'Food & Dining',
    isFreeMoney: false,
    frequency: 'Every time I receive money',
  },
  {
    id: 'wallet_transport',
    name: 'Transport',
    icon: '🚗',
    color: '#06b6d4',
    balance: 800,
    targetAmount: 1000,
    monthlyLimit: 1200,
    allocationPercentage: 10,
    category: 'Transport & Fuel',
    isFreeMoney: false,
    frequency: 'Every time I receive money',
  },
  {
    id: 'wallet_savings',
    name: 'Savings',
    icon: '💰',
    color: '#10b981',
    balance: 2500,
    targetAmount: 2500,
    monthlyLimit: 0,
    allocationPercentage: 20,
    category: 'Savings & Investment',
    isFreeMoney: false,
    frequency: 'Every time I receive money',
  },
  {
    id: 'wallet_college',
    name: 'College',
    icon: '🎓',
    color: '#8b5cf6',
    balance: 1500,
    targetAmount: 2000,
    monthlyLimit: 2000,
    allocationPercentage: 15,
    category: 'College & Education',
    isFreeMoney: false,
    frequency: 'Every time I receive money',
  },
  {
    id: 'wallet_friends',
    name: 'Friends',
    icon: '🤝',
    color: '#ec4899',
    balance: 1000,
    targetAmount: 1500,
    monthlyLimit: 1500,
    allocationPercentage: 10,
    category: 'Friends & Social',
    isFreeMoney: false,
    frequency: 'Every time I receive money',
  },
  {
    id: 'wallet_free',
    name: 'Free Money',
    icon: '✨',
    color: '#3b82f6',
    balance: 2200,
    targetAmount: 0,
    monthlyLimit: 0,
    allocationPercentage: 20,
    category: 'Unallocated Cushion',
    isFreeMoney: true,
    frequency: 'Unallocated reserve',
  },
];

export const INITIAL_TRANSACTIONS = [
  {
    id: 'tx_101',
    merchantName: 'ABC Restaurant',
    amount: 280,
    type: 'debit',
    category: 'Food & Dining',
    walletId: 'wallet_food',
    date: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    status: 'Completed',
    note: 'Lunch with colleagues',
  },
  {
    id: 'tx_102',
    merchantName: 'City Bus Metro',
    amount: 40,
    type: 'debit',
    category: 'Transport & Fuel',
    walletId: 'wallet_transport',
    date: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    status: 'Completed',
    note: 'Daily commute',
  },
  {
    id: 'tx_103',
    merchantName: 'College Canteen',
    amount: 120,
    type: 'debit',
    category: 'Food & Dining',
    walletId: 'wallet_food',
    date: new Date(Date.now() - 22 * 3600 * 1000).toISOString(),
    status: 'Completed',
    note: 'Snacks & chai',
  },
  {
    id: 'tx_104',
    merchantName: 'Sent to Friend (Rohan)',
    amount: 500,
    type: 'debit',
    category: 'Friends & Social',
    walletId: 'wallet_friends',
    date: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    status: 'Completed',
    note: 'Shared weekend dinner split',
  },
  {
    id: 'tx_105',
    merchantName: 'City Pharmacy',
    amount: 180,
    type: 'debit',
    category: 'Health & Wellness',
    walletId: 'wallet_free',
    date: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    status: 'Completed',
    note: 'Vitamin supplements',
  },
];

export const DEMO_MERCHANTS = [
  {
    id: 'm_abc_rest',
    name: 'ABC Restaurant',
    category: 'Food & Dining',
    defaultAmount: 350,
    icon: '🍽️',
    mcc: '5812',
    description: 'Popular diner in downtown',
    matchingWallet: 'wallet_food',
  },
  {
    id: 'm_starbucks',
    name: 'Starbucks Coffee',
    category: 'Food & Dining',
    defaultAmount: 220,
    icon: '☕',
    mcc: '5814',
    description: 'Beverages and pastries',
    matchingWallet: 'wallet_food',
  },
  {
    id: 'm_uber',
    name: 'Uber / City Taxi',
    category: 'Transport & Fuel',
    defaultAmount: 240,
    icon: '🚕',
    mcc: '4121',
    description: 'Ride hailing transit',
    matchingWallet: 'wallet_transport',
  },
  {
    id: 'm_shell',
    name: 'Shell Fuel Station',
    category: 'Transport & Fuel',
    defaultAmount: 500,
    icon: '⛽',
    mcc: '5541',
    description: 'Vehicle petrol / diesel refill',
    matchingWallet: 'wallet_transport',
  },
  {
    id: 'm_apollo',
    name: 'Apollo Pharmacy',
    category: 'Health & Wellness',
    defaultAmount: 420,
    icon: '💊',
    mcc: '5912',
    description: 'Medicine & healthcare supplies',
    matchingWallet: 'wallet_free',
  },
  {
    id: 'm_campus_books',
    name: 'Campus Book Store',
    category: 'College & Education',
    defaultAmount: 650,
    icon: '📚',
    mcc: '5942',
    description: 'Semester reference books & stationery',
    matchingWallet: 'wallet_college',
  },
  {
    id: 'm_barber',
    name: 'XYZ Barber & Salon',
    category: 'Personal Care',
    defaultAmount: 300,
    icon: '💈',
    mcc: '7230',
    description: 'Grooming & haircut',
    matchingWallet: 'wallet_free',
  },
  {
    id: 'm_zara',
    name: 'Zara Lifestyle',
    category: 'Shopping & Apparel',
    defaultAmount: 1200,
    icon: '🛍️',
    mcc: '5651',
    description: 'Clothing & lifestyle',
    matchingWallet: 'wallet_free',
  },
  {
    id: 'm_friend_rohan',
    name: 'Pay Friend (Rohan)',
    category: 'Friends & Social',
    defaultAmount: 500,
    icon: '👤',
    mcc: '0000',
    description: 'Personal peer-to-peer payback',
    matchingWallet: 'wallet_friends',
  },
];
